[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
log = "0.4.21"
log4rs = { version = "1.3.0", features = ["gzip"] }
config = { version = "0.14.0", features = ["toml"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.12"
anyhow = "1.0.81"
tauri = { version = "1.6.1", features = ["config-json5", "dialog-all", "path-all", "process-command-api", "shell-sidecar"] }
tempfile = "3.10.1"
windows = { version = "0.54.0", features = ["Win32_System_Com", "Win32_System_Ole"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
