refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: '{d(%Y-%m-%dT%H:%M:%S)} [{f}:{L}] {h({l})} {M}:{m}{n}'

  rollingfile:
    kind: rolling_file
    path: '$ENV{GENDOC_LOG_PATH}/app.log'
    encoder:
      pattern: '[{d(%Y-%m-%dT%H:%M:%S)} {h({l}):<5.5} {M}] {m}{n}'
    policy:
      trigger:
        kind: time
        interval: 1 day
        modulate: true
      roller:
        kind: fixed_window
        pattern: '$ENV{GENDOC_LOG_PATH}/app-{}.log.gz'
        base: 1
        count: 7

root:
  level: info
  appenders:
    - stdout
    - rollingfile
